package CalcApp;


/**
* CalcApp/CalcInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcInterface.idl
* jueves 12 de abril de 2018 14H39' VET
*/

public interface CalcInterface extends CalcInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalcInterface
